### ISSUE TITLE
Motion profiling for an arm

### ISSUE THREAD

**Issue by J-Palomino** [DoF-6413/chargedUp#15]
It would be nice to have a motion profiling set up for the arm but we don't necessarily need that for the drivetrain. This is something Steve knows about and he has the link.

**Comment by El1zabethS** [comment]
1-23-23
Currently it is at a point where it only needs to be tuned.

Make sure to set Max Velocity and Max Acceleration to a value other than 0
Tune PID First
(P, then I (optional), then D (Optional))
Then Feedforward

You can use System Identification Tool (_sysid 2023_)

**Comment by El1zabethS** [comment]
1-29-23:
Created as a command, not subsystem:
It works but will need to be tuned
Output returns strange values?

**Comment by J-Palomino** [comment]
Motion profile in and working for arm still needs tuning
