### ISSUE TITLE
Answer electrical questions in slack

### ISSUE THREAD

**Issue by El1zabethS** [DoF-6413/chargedUp#20]
Audi asked us some electrical questions in slack can someone please answer her and post the answers in programming channel:

1. How many sensors do we plan on using?
2. What type of sensors are we planning on using?
3. How many motors do we plan on using?
4. What types of motors do we plan on using?
5. Any non FRC standard electronics that we plan on using?
6. What type of camera?
7. Any other electronics we will use that are like the raspberry pie?
8. Anything else you wanna do want to add on electrically?

**Comment by alt09** [comment]
ok I can help

**Comment by El1zabethS** [comment]
1. ??
2. Absolute encoders on arm actuators
3. ???
4. Neo and Falcon 500s
5. \(O-O)/
6. ??
7. \(O-O)/
8. ??

**Comment by alt09** [comment]
1. At least 19(including sensors of the motors )?
2. Absolute encoders, ultrasonic sensor vision processing, limit switches
3. 14
4. Neo and Falcon 500
5. ethernet switch ,raspberry pi
6. Arducam
7. ethernet switch
8. fans heat sinks
