### ISSUE TITLE
Add ultrasonic sensor to sensor subsystem

### ISSUE THREAD

**Issue by nancyesquivel10** [DoF-6413/chargedUp#21]
[Ultrasonic sensor](https://www.andymark.com/products/ultrasonic-proximity-sensor-ez-mb1013-maxbotix)

**Comment by J-Palomino** [comment]
Lets document what happened here as I recall we haven't been able to get it working yet or get any sort of signal in. it is wired for analog out put we know that. What else do we know?

**Comment by alt09** [comment]
I did this with Liz
