### ISSUE TITLE
odometry and pose estimation 

### ISSUE THREAD

**Issue by nancyesquivel10** [DoF-6413/chargedUp#23]

**Comment by J-Palomino** [comment]
This is the tutorial on setting up the 2d widget for pose estimation: 
https://docs.wpilib.org/en/stable/docs/software/dashboards/glass/field2d-widget.html

This is where we can find the import for odometry for differential drivetrains:
https://github.com/wpilibsuite/allwpilib/blob/a610379965680a8f9214d5f0db3a8e1bc20d4712/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecontroller/Drivetrain.java#L11

here is this years field image: https://github.com/wpilibsuite/allwpilib/blob/main/fieldImages/src/main/native/resources/edu/wpi/first/fields/2023-field.png

Lines 107-125 show the pose getters and setters:
https://github.com/wpilibsuite/allwpilib/blob/a610379965680a8f9214d5f0db3a8e1bc20d4712/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecontroller/Drivetrain.java#L103

**Comment by nancyesquivel10** [comment]
- [ ]  add autoutils.java file similar to this : https://github.com/TitaniumTitans/2023ChargedUp/blob/8fe39426c9005e9c2c54fe53a4299186bf332bc9/src/main/java/frc/robot/commands/Autonomous/AutoUtils.java#L46
- [ ]  change custom path to your own path like this : https://github.com/TitaniumTitans/2023ChargedUp/blob/8fe39426c9005e9c2c54fe53a4299186bf332bc9/src/main/java/frc/robot/commands/Autonomous/AutoUtils.java#L26
- [ ] instead of ppswerve controller use ramsette controller: https://github.com/TitaniumTitans/2023ChargedUp/blob/8fe39426c9005e9c2c54fe53a4299186bf332bc9/src/main/java/frc/robot/commands/Autonomous/AutoUtils.java#L34
- [ ] add to list of autos https://github.com/TitaniumTitans/2023ChargedUp/blob/8fe39426c9005e9c2c54fe53a4299186bf332bc9/src/main/java/frc/robot/RobotContainer.java#L115
- [ ] add auto constants: https://github.com/TitaniumTitans/2023ChargedUp/blob/8fe39426c9005e9c2c54fe53a4299186bf332bc9/src/main/java/frc/robot/Constants.java#L84

**Comment by nancyesquivel10** [comment]
robot pose
https://docs.wpilib.org/en/stable/docs/software/kinematics-and-odometry/differential-drive-odometry.html 
ramset command 
https://github.com/mjansen4857/pathplanner/blob/main/pathplannerlib/src/main/java/com/pathplanner/lib/commands/PPRamseteCommand.java
Diff drive Odometry example 
https://github.com/wpilibsuite/allwpilib/blob/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Drivetrain.java 
Pathplanner java usage 
https://github.com/mjansen4857/pathplanner/wiki/PathPlannerLib:-Java-Usage
