### ISSUE TITLE
Install April tags on Field elements

### ISSUE THREAD

**Issue by J-Palomino** [DoF-6413/chargedUp#29]
A reminder on the location of the various IDs on the field:
• Red Alliance Community (right to left) – IDs 1, 2, 3
• Blue Alliance Double Substation – ID 4
• Red Alliance Double Substation – ID 5
• Blue Alliance Community (right to left) – IDs 6, 7, 8

Since we are only building half the field we should make them interchangeable

Make sure to use [This PDF](https://firstfrc.blob.core.windows.net/frc2023/FieldAssets/TeamVersions/AprilTags-UserGuideandImages.pdf) to position the tags correctly on the field elements.

**Comment by alt09** [comment]
I finished that
