### ISSUE TITLE
Autonomous that gets out of community zone and balances on charging station

### ISSUE THREAD

**Issue by nancyesquivel10** [DoF-6413/chargedUp#45]
Steps: 
1) Start on left of the blue side 
2) Drive straight out of community zone about 5 ft 
3) Turn right 90 degrees
4) Go straight forward about 5 ft 
5) Turn right 90 degrees 
6) Drive straight forward and balance 3-4 ft

**Comment by El1zabethS** [comment]
coved in diff issue

**Comment by J-Palomino** [comment]
Has this been tested?

**Comment by El1zabethS** [comment]
We went through and closed a bunch of auton issues and put them in one (balancing and moving are broad enough where we decided we dont need to have issues that map out the specific path) we can always reopen if needed
