### ISSUE TITLE
Feat add ramsete controller to drive train

### ISSUE THREAD

**Issue by alt09** [DoF-6413/chargedUp#51]
this is a little explanation of what is a Ramsete controller and how is used
https://docs.wpilib.org/en/stable/docs/software/advanced-controls/trajectories/ramsete.html
this is a example to how we can use the Ramsete controller in the code in GitHub 
https://github.com/wpilibsuite/allwpilib/blob/main/wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java#L154

when this is done we will be able to control our drive train using  a Ramset controller that accepts a path as a argument

**Comment by alt09** [comment]
its a example for a team
https://github.com/team8/FRC-2022-Public/blob/main/src/main/java/com/palyrobotics/frc2022/subsystems/controllers/drive/RamseteDriveController.java#L17

**Comment by El1zabethS** [comment]
All variables are set up, we are just trying to get it to run now. Next step: Update motor safety.

**Comment by El1zabethS** [comment]
motor saftey done. make sure to add ALL values for ramsete controllers :>
