### ISSUE TITLE
Arm Reset Position Command 

### ISSUE THREAD

**Issue by nancyesquivel10** [DoF-6413/chargedUp#70]
- [x] Rotation (Neo Absolute Encoder) 

- [x] Telescoper (Falcon current limit)

**Comment by nancyesquivel10** [comment]
Description: reset it to zero position so it consistently has the same encoder values

**Comment by El1zabethS** [comment]
Created one for telescoper, needs testing

**Comment by El1zabethS** [comment]
Finished!
