### ISSUE TITLE
Position Presets with Arm

### ISSUE THREAD

**Issue by El1zabethS** [DoF-6413/chargedUp#73]
Sets Positions for the Arm to be at so drivers don't have to manually do it
- [ ]  Place High Grid
- [ ]  Place Mid Grid 
- [ ]  Place Low Grid 
- [ ]  Pickup HP Station 
- [ ]  Pickup Floor 

Create PID Go To Functions:
- [x] Rotator
- [ ] Telescoper

**Comment by J-Palomino** [comment]
It is possible to swing the arm all the way through to get positions on the other side of robot Incase a cone is flipped?

**Comment by El1zabethS** [comment]
Ooh, definetly. If we had cameras on both sides of the robot, maybe we can have the arm swing to either side depending on which side sees an april tag

**Comment by El1zabethS** [comment]
As of now, the arm isn't gonna swing through, also we have trapazoidal motion profiling built for the arm but not at all tested. Will need LOTS of testing. Might be worth created a backup function w/o pid?
